from neuroforge_core.domain.interfaces.model_trainer import IModelTrainer
from neuroforge_core.domain.interfaces.i_model_compiler import IModelCompiler
from neuroforge_core.domain.interfaces.i_model_evaluator import IModelEvaluator